/* RecipeHub detailed bilingual recipe content. Recipe set intentionally unchanged. */
(function(){
  const R={
    biryani:{en:{title:'Chicken Biryani',intro:'A Pakistani-Indian style chicken biryani built around fluffy basmati rice, a properly reduced chicken masala and a gentle final dum. The method focuses on texture, seasoning and the small home-kitchen decisions that make the finished pot taste balanced rather than heavy.',ingredients:['500 g bone-in chicken','2 cups basmati rice','1 large onion, thinly sliced','2 medium tomatoes, chopped','1 cup plain yogurt','2 tbsp oil','1 tbsp ginger-garlic paste','1–2 tbsp biryani masala','1 tsp cumin seeds','1/2 tsp turmeric','1/2 tsp chili powder','Salt to taste','1 green chili, sliced','1/2 cup fresh coriander and mint','1 tbsp lemon juice'],times:'Prep 25 min • Cook 50 min • Rest 5 min',steps:[
      'Wash the basmati rice several times until the water is mostly clear, then soak it for 20 minutes. Drain well. This short soak helps the grains cook evenly without becoming fragile during layering.',
      'Heat oil in a heavy pot and fry the sliced onion slowly until deep golden. Remove about one third for the final layer. Do not burn it: bitter fried onion can overpower the entire masala.',
      'Add ginger-garlic paste and chicken to the remaining onion. Cook for 6–8 minutes, turning the pieces so they take on colour and the raw aroma disappears. Keep the heat medium rather than scorching the spices.',
      'Add tomatoes, yogurt, biryani masala, cumin, turmeric, chili powder and salt. Cook uncovered until the tomatoes collapse and the masala becomes thick enough to coat the chicken. The oil should begin appearing around the edges.',
      'Boil plenty of salted water and add the soaked rice. Cook until the grains are roughly 80 percent done: the outside should be tender but the centre should still have a small bite. Drain immediately and spread briefly so steam escapes.',
      'Layer the drained rice over the chicken without stirring the two layers together. Scatter fried onion, mint, coriander, green chili and lemon juice across the top. A few drops of rose or kewra water may be used, but keep it subtle.',
      'Cover tightly and cook on the lowest heat for about 15 minutes. If your pot is thin, place it on a tawa to protect the bottom. Turn off the heat and leave the covered pot alone for another 5 minutes.',
      'Open the lid and fluff from the sides with a wide spoon, lifting rather than mixing aggressively. Taste one grain and one chicken piece before serving; adjust only with a little salt or lemon if genuinely needed.'
    ],idea:'Layer the biryani with a small pinch of crushed dried mint between the rice and chicken. It gives the dum a fresh, earthy aroma without turning the dish into a mint-heavy biryani.',serve:'Serve with chilled raita, cucumber-onion salad, lemon wedges and a little mint chutney. For a fuller Pakistani meal, add a simple kachumber rather than another rich curry.',tips:['Mushy rice: the rice was boiled too long; drain around 80 percent cooked.','Watery masala: reduce the chicken mixture uncovered before layering.','Dry chicken: keep enough masala around the chicken and avoid excessive high heat.','Too salty: do not add more salt until both the rice and masala are combined; a little unsalted yogurt on the side can balance the plate.','Weak flavour: season the rice water and chicken separately instead of trying to repair everything at the end.']},
    'karahi-gosht':{en:{title:'Karahi Gosht',intro:'A Pakistani-style karahi where meat is cooked until tender and the tomato masala is reduced by patient bhunai. The finished sauce should cling to the meat, with fresh ginger and green chili arriving at the end for contrast.',ingredients:['750 g mutton or beef','3 ripe tomatoes, chopped','1 medium onion, sliced','3 tbsp cooking oil','1 tbsp ginger-garlic paste','2 green chilies','1 tsp cumin','1 tsp coriander powder','1 tsp chili powder','1/2 tsp turmeric','Salt','2 tbsp fresh coriander','2 tbsp julienned ginger'],times:'Prep 15 min • Cook 60–75 min • Rest 5 min',steps:[
      'Pat the meat dry and heat the karahi until properly hot. Add oil and brown the meat in batches if necessary. Browning creates a deeper base; crowding the pan makes the meat release water and steam instead.',
      'Lower the heat slightly and add onion, ginger and garlic. Cook until the onion softens and the raw ginger-garlic smell disappears. If using tender mutton, keep the onion modest so tomato remains the main flavour.',
      'Add chopped tomatoes, cumin, coriander powder, chili powder, turmeric and salt. Cover for 8–10 minutes so the tomatoes break down and release moisture. Stir occasionally so the bottom does not catch.',
      'Continue cooking until the meat becomes tender, adding small splashes of hot water only when needed. Mutton may need close to an hour; beef can take longer. Tenderness, not a fixed clock, is the final test.',
      'Once the meat is cooked, remove the lid and raise the heat slightly. Bhuno the curry until excess water evaporates and the tomato mixture becomes glossy. Scrape the bottom gently rather than adding water automatically.',
      'Taste the masala and adjust salt or chili before the final garnish. If the tomatoes are sharply acidic, a tiny pinch of sugar can round the edge, but the finished karahi should still taste savoury and bright.',
      'Add sliced green chili and half the fresh ginger during the final two minutes. This keeps their aroma lively. Turn off the heat once the oil lightly shines at the edges rather than frying the masala dry.',
      'Rest the karahi for 5 minutes, then scatter coriander and remaining ginger over the top. Serve directly from the karahi while hot so the concentrated tomato aroma reaches the table.'
    ],idea:'Reserve a few strips of ginger and green chili until the last minute. Their fresh heat sits on top of the deep bhunai flavour and gives this version a distinctive Pakistani dhaba-style finish.',serve:'Serve with hot naan, roti or butter naan, plus sliced onion, lemon and plain yogurt. The rich masala benefits from a crisp, acidic side.',tips:['Meat still hard: add hot water in small amounts and continue covered cooking; do not rush with high heat.','Gravy too thin: uncover and bhuno until the tomato mixture clings to the meat.','Burnt bottom: transfer the unburnt upper curry to a clean pan and continue gently; do not scrape bitter solids from the base.','Too sour: add a very small pinch of sugar and cook for two minutes.','Too oily: spoon off only the visible excess oil after resting; do not remove all of it because the glossy finish is part of karahi character.']},
    'daal-chawal':{en:{title:'Daal Chawal',intro:'A comforting Pakistani home-style combination of soft lentils, fragrant tempering and fluffy rice. The goal is a dal that is creamy enough to coat rice but still has a fresh, savoury tarka on top.',ingredients:['1 cup masoor or moong dal','1 cup basmati rice','1 small onion','1 tomato','4 garlic cloves','1 tsp cumin seeds','1/2 tsp turmeric','1/2 tsp red chili powder','2 tbsp oil or ghee','Salt','Fresh coriander','1 green chili'],times:'Prep 10 min • Cook 35–40 min • Rest 5 min',steps:[
      'Rinse the dal until the water runs reasonably clear and check for any stones. Soaking for 15–20 minutes is optional but helps it cook more evenly, especially if the dal is older.',
      'Place the dal in a pot with about three cups of water, turmeric and a little salt. Bring it to a gentle boil, skim obvious foam and cook until the lentils are soft enough to break with the back of a spoon.',
      'Rinse the rice separately and cook it in plenty of salted water until each grain is tender but not swollen or sticky. Drain if using the absorption-free method, then cover for five minutes before fluffing.',
      'For the tarka, heat oil or ghee and add cumin. When it crackles, add sliced garlic and onion. Cook until the onion is light golden. Add chopped tomato, chili powder and green chili and cook until the tomato softens.',
      'Whisk the cooked dal gently. If it is too thick, add hot water a few tablespoons at a time. If it is watery, simmer uncovered. The ideal consistency should flow slowly from a spoon rather than sit like a paste.',
      'Pour the hot tarka over the dal and listen for the brief sizzle. Reserve a spoonful of the tarka oil for the top if you want a more aromatic finish. Taste for salt after the tarka has been mixed through.',
      'Rest the dal for five minutes so the tempering settles into the lentils. Meanwhile fluff the rice with a fork or flat spoon, keeping the grains separate rather than repeatedly stirring them.',
      'Serve the rice first and ladle dal over one side so the grains remain visible. Finish with coriander, green chili and lemon if desired. Keep extra tarka or yogurt at the table for personal adjustment.'
    ],idea:'Make a tiny second tarka using only cumin, garlic and a little ghee and spoon it over each serving. It creates a fresh aromatic top note without making the whole pot greasy.',serve:'Serve hot with basmati rice, sliced onion, lemon, green chili and plain yogurt. A little mango pickle works especially well with the soft dal.',tips:['Dal too thick: loosen with hot water, not cold water.','Dal too thin: simmer uncovered for a few minutes.','Burnt tarka: discard the burnt oil and make a fresh small tempering; burnt garlic will make the entire dal bitter.','Rice sticky: rinse better next time and avoid overcooking; spread it briefly after draining.','Flat flavour: check salt first, then add lemon at the table rather than adding large amounts during cooking.']},
    nihari:{en:{title:'Nihari',intro:'Slow-cooked Pakistani nihari with tender meat, a deep spice base and a lightly thickened broth. This version focuses on controlled heat and finishing aromatics so the gravy stays rich but not pasty.',ingredients:['750 g beef shank or stew meat','2 tbsp oil or ghee','1 large onion','1 tbsp ginger-garlic paste','2 tbsp nihari masala','1/2 tsp chili powder','1/4 tsp turmeric','2 tbsp wheat flour','6 cups hot water','Salt','Fresh ginger','Green chilies','Coriander','Lemon'],times:'Prep 20 min • Cook 2–2.5 hr • Rest 10 min',steps:[
      'Trim only excess surface fat from the beef and cut it into large pieces. Heat oil in a heavy pot and brown the meat in batches. Proper browning gives the broth a deeper savoury base without requiring artificial colour.',
      'Add sliced onion and cook until golden. Stir in ginger-garlic paste and fry briefly until fragrant. Keep the heat moderate because burnt onion or garlic will remain noticeable through the long cooking time.',
      'Add nihari masala, chili powder, turmeric and salt. Stir for 30–40 seconds, then add the hot water. Scrape the base gently to dissolve the browned flavour into the broth.',
      'Cover and simmer very gently until the beef is fork-tender. Depending on the cut, this can take two hours or more. Check occasionally and add hot water if the level falls too far below the meat.',
      'Mix wheat flour with cool water in a separate bowl until completely smooth. Pour it slowly into the simmering nihari while stirring continuously. This prevents flour lumps and lets you control the final thickness.',
      'Simmer uncovered for another 10–15 minutes. The gravy should lightly coat a spoon but still pour easily. If it becomes too thick, loosen it with hot water rather than adding more flour.',
      'Turn off the heat and let the nihari rest for about 10 minutes. Taste for salt and spice after resting because the broth becomes more integrated and the surface fat settles naturally.',
      'Serve in bowls with fresh ginger, coriander, green chili and lemon. Encourage diners to add the garnishes gradually; the fresh ginger and acid are important because they balance the slow-cooked richness.'
    ],idea:'Finish each bowl with a very small spoon of ginger-infused oil made by warming oil with fresh ginger for one minute. It adds aroma at the table without changing the main pot.',serve:'Serve piping hot with naan or khameeri roti, julienned ginger, coriander, green chili and lemon. Keep the garnishes generous because they cut through the rich broth.',tips:['Gravy too thick: add hot water gradually and simmer for two minutes.','Gravy too thin: simmer uncovered; do not keep adding flour.','Meat tough: continue gentle cooking; high heat can tighten the outside without tenderising the centre.','Too salty: dilute with unsalted hot water and a little extra cooked meat or broth if available.','Burnt bottom: move the upper liquid and meat to a clean pot without scraping the blackened base.']},
    'palak-paneer':{en:{title:'Palak Paneer',intro:'Creamy Indian-style palak paneer with bright spinach, soft paneer and a balanced garlic-spice base. The method keeps the spinach fresh rather than overcooking it into a dull, heavy puree.',ingredients:['500 g fresh spinach','300 g paneer','1 small onion','2 tomatoes','1 tbsp ginger-garlic paste','1 green chili','1 tsp cumin','1/2 tsp turmeric','1 tsp coriander powder','1/2 tsp garam masala','2 tbsp oil','2 tbsp cream','Salt','1 tsp lemon juice'],times:'Prep 15 min • Cook 25 min • Rest 5 min',steps:[
      'Wash the spinach thoroughly and remove thick stems. Blanch it in boiling water for about two minutes, then transfer immediately to cold water. This brief cooling step helps retain a fresher green colour and stops carryover cooking.',
      'Blend the cooled spinach with green chili and a splash of water until smooth but not watery. Keep the puree aside. If you prefer texture, leave a small portion of spinach roughly chopped instead of blending everything.',
      'Cut paneer into bite-size cubes. Warm a little oil in a pan and lightly sear the cubes until the edges turn pale golden. Do not fry them hard; over-browned paneer can become chewy after it sits in the gravy.',
      'Heat oil in the main pan and add cumin. Add onion and cook until soft, then add ginger-garlic paste. Stir until fragrant before adding chopped tomatoes, turmeric and coriander powder.',
      'Cook the tomato mixture until soft and the oil begins to separate. This is the flavour base, so do not rush it. If it catches, lower the heat and add a tablespoon of water.',
      'Add the spinach puree and simmer gently for 5–7 minutes. Keep the heat moderate; prolonged hard boiling can darken the spinach and flatten its fresh flavour.',
      'Add paneer, garam masala, salt and cream. Simmer for another 3–4 minutes, just long enough for the paneer to warm and absorb some gravy. Finish with lemon juice for a small lift.',
      'Rest for five minutes before serving. Taste once more and adjust salt or lemon. The final gravy should be creamy and spoonable, with enough body to cling to paneer without becoming paste-like.'
    ],idea:'Blend one tablespoon of the seared paneer edges into the spinach gravy. It adds a subtle roasted dairy note and gives the sauce a naturally fuller body without extra flour.',serve:'Serve with naan, roti, jeera rice or plain basmati rice. A small bowl of cucumber raita makes the meal lighter.',tips:['Spinach dull: avoid long boiling after blending.','Paneer rubbery: sear lightly and keep the final simmer short.','Gravy too thick: loosen with warm water or a little milk.','Gravy too thin: simmer gently uncovered for a few minutes.','Too bitter: check salt and add a little cream or lemon rather than adding sugar immediately.']},
    'butter-chicken':{en:{title:'Butter Chicken',intro:'A smooth Indian-style butter chicken with charred-looking chicken pieces, tomato gravy, butter and cream. The key is to cook the tomato base until its raw acidity disappears before finishing with dairy.',ingredients:['600 g boneless chicken','1/2 cup yogurt','1 tbsp lemon juice','1 tbsp ginger-garlic paste','1 tsp chili powder','1 tsp garam masala','2 tbsp butter','1 tbsp oil','3 tomatoes, pureed','1/2 cup cream','1 tsp kasuri methi','1 tsp sugar, optional','Salt'],times:'Prep 20 min • Marinate 30 min+ • Cook 35 min',steps:[
      'Cut the chicken into even pieces so they cook at the same rate. Mix with yogurt, lemon juice, ginger-garlic, chili powder, garam masala and salt. Rest for at least 30 minutes; longer marination gives a more seasoned centre.',
      'Heat a pan or grill until hot. Cook the marinated chicken in batches so the surface browns instead of steaming. It does not need to be completely finished at this stage if you will simmer it later in the sauce.',
      'In a separate pan, melt butter with a little oil to reduce the chance of burning. Add tomato puree and cook patiently until it thickens and the raw tomato smell disappears. The colour should deepen slightly.',
      'Add a little warm water if the tomato base becomes too tight, then simmer until smooth. If you want a restaurant-style texture, blend and strain the sauce before returning it to the pan.',
      'Add the cooked chicken and simmer gently for 8–10 minutes. The chicken should finish cooking in the sauce and take on its flavour. Avoid a hard boil because it can split the dairy added later.',
      'Lower the heat and add cream, remaining butter and kasuri methi crushed between your palms. Add a small pinch of sugar only if the tomatoes are unusually sharp; sweetness should round the sauce, not dominate it.',
      'Taste for salt, chili and acidity. If the sauce is too rich, a few drops of lemon can brighten it. If it is too sharp, another spoon of cream or a little butter can soften the edge.',
      'Rest the curry for five minutes before serving. The sauce thickens slightly as it cools, so judge the final consistency after the rest rather than over-reducing it while hot.'
    ],idea:'Crush the kasuri methi between your palms and add half during cooking and half just before serving. The two-stage addition gives both depth and a fresh dried-herb aroma.',serve:'Serve with butter naan, garlic naan, roti or basmati rice. Finish with coriander and a small swirl of cream rather than flooding the plate with extra butter.',tips:['Sauce too sour: cook longer, then balance with a little cream or tiny sugar pinch.','Sauce split: lower heat and whisk in a tablespoon of warm water.','Chicken dry: avoid overcooking before it enters the sauce.','Too thick: loosen with warm water or unsalted stock.','Burnt tomato: do not scrape the burnt base into the sauce; transfer the clean upper mixture to another pan.']},
    'chicken-tikka':{en:{title:'Chicken Tikka',intro:'Juicy Pakistani-Indian chicken tikka with a yogurt-spice marinade and high-heat cooking. The recipe is designed for an oven, grill or air fryer and explains how to avoid dry chicken while still getting browned edges.',ingredients:['600 g boneless chicken thigh','1/2 cup thick yogurt','1 tbsp lemon juice','1 tbsp ginger-garlic paste','1 tsp cumin','1 tsp coriander powder','1 tsp chili powder','1/2 tsp turmeric','1 tsp tikka masala','1 tbsp oil','Salt','1 tbsp gram flour'],times:'Prep 15 min • Marinate 2–8 hr • Cook 15–20 min',steps:[
      'Use boneless chicken thigh for the juiciest home result and cut it into medium, even pieces. Pat the chicken dry first so the marinade clings rather than becoming watery.',
      'Mix yogurt, lemon juice, ginger-garlic, cumin, coriander, chili, turmeric, tikka masala, gram flour, oil and salt. Gram flour absorbs excess moisture and helps the coating brown during high-heat cooking.',
      'Coat every chicken piece and cover. Marinate for at least two hours in the refrigerator. If marinating overnight, do not add excessive lemon because prolonged acid exposure can change the texture of the chicken.',
      'Bring the chicken out shortly before cooking. Thread pieces onto skewers with small gaps so hot air can reach the sides. If using an oven, place them on a rack over a tray rather than directly in a pool of marinade.',
      'Cook at high heat, turning once or twice, until browned and the thickest piece reaches a safe fully-cooked centre. Exact time varies with piece size and appliance, so use colour and doneness together rather than the clock alone.',
      'For extra char, move the cooked tikka briefly under a hot grill or broiler. Watch closely because the yogurt marinade can darken quickly. A light brush of oil before the final minute improves surface colour.',
      'Rest the chicken for five minutes before serving. This short pause lets the juices redistribute and prevents the first cut from releasing all the moisture onto the plate.',
      'Finish with lemon, chaat masala if desired, sliced onion and fresh coriander. Serve immediately while the outside is smoky and the centre remains tender.'
    ],idea:'Add a teaspoon of roasted gram flour to the marinade instead of extra oil. It creates a thin, clingy coating that browns well and gives the tikka a subtle nutty aroma.',serve:'Serve with mint chutney, lemon, onion rings and warm naan. It also works well as a filling for a paratha roll.',tips:['Dry chicken: use thigh pieces and do not overcook.','Marinade sliding off: dry the chicken and use thick yogurt.','Too charred outside: lower the rack or heat and finish more gently.','Too salty: avoid adding extra salt after marination; serve with unsalted yogurt or salad.','Undercooked centre: return to heat in short intervals and check the thickest piece rather than judging the smallest piece.']},
    'gulab-jamun':{en:{title:'Gulab Jamun',intro:'Soft gulab jamun made from milk powder dough and soaked in fragrant sugar syrup. The important skills are gentle dough handling, low frying heat and a syrup that is warm enough to enter the sweets without crystallising.',ingredients:['1 cup milk powder','3 tbsp plain flour','1/2 tsp baking powder','2 tbsp ghee','3–5 tbsp milk, as needed','1.5 cups sugar','1.5 cups water','3 cardamom pods','1 tsp rose water, optional','Oil or ghee for frying'],times:'Prep 20 min • Fry 20 min • Soak 1–2 hr',steps:[
      'Make the syrup first so it is ready and warm when the fried jamun are finished. Boil sugar, water and cardamom for about 5–7 minutes until slightly sticky but still pourable. Add rose water after turning off the heat.',
      'Mix milk powder, flour and baking powder. Rub in ghee, then add milk one spoon at a time. Stop as soon as a soft dough forms. Overworking the mixture can make the finished jamun dense.',
      'Rest the dough for five minutes. Grease your palms lightly and shape small smooth balls without cracks. Keep them covered while shaping the rest so the surface does not dry out.',
      'Heat oil or a mixture of oil and ghee on low to medium-low heat. Test with a tiny piece of dough: it should rise slowly, not shoot to the surface immediately. High heat browns the outside before the centre cooks.',
      'Fry the balls in small batches, moving them gently so they colour evenly. Aim for a deep golden-brown shade rather than a dark brown crust. Remove them and let excess fat drain briefly.',
      'Warm the sugar syrup if it has cooled too much, but do not boil it aggressively. Place the warm fried jamun into the warm syrup and turn them carefully so the surface begins absorbing liquid.',
      'Let the jamun soak for at least one hour. They should become visibly larger and soft when pressed lightly. If the syrup is extremely thick, add a little warm water and reheat gently before soaking.',
      'Serve warm or at room temperature with a little syrup, chopped pistachio or a small spoon of cream. Do not squeeze the jamun hard when plating because that pushes out the absorbed syrup.'
    ],idea:'Add one crushed cardamom seed directly to the dough as well as the syrup. The aroma becomes noticeable from the centre of the sweet instead of only on the surface.',serve:'Serve warm with syrup and pistachio, or pair with vanilla ice cream for a richer dessert.',tips:['Cracked jamun: the dough is too dry; add milk a few drops at a time.','Dark outside/raw centre: lower the frying heat.','Hard jamun: dough was overworked or syrup was too cold/thick.','Crystallised syrup: avoid prolonged boiling after the sugar dissolves.','Jamun not absorbing: keep syrup warm and allow a longer soaking time.']},
    'chana-masala':{en:{title:'Chana Masala',intro:'Bold Indian chana masala with tender chickpeas, a properly cooked onion-tomato base and bright finishing flavours. A portion of the chickpeas is mashed into the gravy to thicken it naturally.',ingredients:['3 cups cooked chickpeas','1 large onion','3 tomatoes','1 tbsp ginger-garlic paste','1 tsp cumin','1 tsp coriander powder','1/2 tsp turmeric','1 tsp chili powder','1 tsp chana masala','2 tbsp oil','Salt','Fresh coriander','1 tbsp lemon juice'],times:'Prep 15 min • Cook 30 min • Rest 5 min',steps:[
      'Drain and rinse cooked chickpeas if using canned beans. Reserve a little of their cooking liquid or plain water. The chickpeas should be tender enough to mash lightly; firm beans will not develop the right creamy texture in the gravy.',
      'Heat oil and add cumin. Add finely chopped onion and cook until golden at the edges. This takes several minutes and is worth the time because lightly cooked onion leaves the curry sweet and harsh.',
      'Add ginger-garlic paste and fry briefly. Stir in tomatoes, turmeric, coriander, chili powder and salt. Cook uncovered until the tomato mixture thickens and oil begins to show around the sides.',
      'Add chana masala and a splash of water, then cook for another minute so the spice blend hydrates in the masala. Avoid burning dry spices directly against the hot pan.',
      'Add chickpeas and enough water to create a spoonable curry. Simmer gently for 12–15 minutes, stirring occasionally. The beans should take on the masala rather than remain separate from it.',
      'Mash a small handful of chickpeas against the side of the pan. This releases starch and thickens the gravy naturally. Add more water if the curry becomes tighter than you want.',
      'Taste after simmering and adjust salt, chili and lemon. If the tomatoes are very acidic, cook a little longer before considering a tiny pinch of sugar. The curry should remain savoury and tangy.',
      'Turn off the heat and rest for five minutes. Finish with coriander and lemon. The resting time allows the masala to cling to the chickpeas and makes the texture more cohesive.'
    ],idea:'Mash two tablespoons of chickpeas with a spoonful of the cooked masala, then stir that paste back into the pot. It gives a naturally thick, restaurant-like coating without flour or cream.',serve:'Serve with bhatura, puri, roti, naan or basmati rice. Add raw onion, lemon and coriander for freshness.',tips:['Gravy thin: mash more chickpeas and simmer uncovered.','Beans firm: simmer longer with a little hot water.','Too sour: cook the tomato base longer and balance carefully with a tiny sugar pinch if needed.','Too salty: add more unsalted chickpeas or water and simmer.','Flat taste: check salt and finish with lemon rather than adding more spice powder alone.']},
    'seekh-kebab':{en:{title:'Seekh Kebab',intro:'Juicy Pakistani seekh kebab made from seasoned minced meat with a firm texture that holds to the skewer. The biggest practical detail is moisture control: squeezed onion and chilled mince make shaping much easier.',ingredients:['500 g beef or lamb mince','1 small onion, finely chopped','2 green chilies, finely chopped','2 tbsp coriander','1 tbsp ginger-garlic paste','1 tsp cumin','1 tsp coriander powder','1 tsp chili flakes','1/2 tsp garam masala','1 tbsp lemon juice','Salt','1 tbsp oil','1 tbsp dried fenugreek leaves, optional'],times:'Prep 20 min • Chill 30 min • Cook 12–15 min',steps:[
      'Finely chop the onion and squeeze it hard in a clean cloth or paper towel. Remove as much liquid as possible. Wet onion is one of the main reasons homemade seekh kebab slips from the skewer.',
      'Combine mince, onion, chilies, coriander, ginger-garlic, cumin, coriander powder, chili flakes, garam masala, lemon, salt and optional dried fenugreek. Mix firmly for several minutes until the mixture becomes slightly sticky.',
      'Cover and refrigerate for 30 minutes. The cold mixture becomes easier to handle and the fat firms slightly, helping the kebabs keep their shape when they first hit the hot pan or grill.',
      'Wet your hands lightly and press a portion around a flat skewer, making an even cylinder rather than a thick lump. Leave no loose gaps because loose mince can split during turning.',
      'Heat the grill or pan well before cooking. Place the kebabs down and leave them alone for the first few minutes so the surface sets. Turn gently once a browned crust forms.',
      'Continue cooking until the centre is fully cooked and the juices run clear. Brush with a little oil only if the surface looks dry. Repeatedly pressing the kebab pushes out the moisture you want to keep.',
      'If using a pan, cook in batches rather than crowding it. After each batch, remove browned bits that could burn before starting the next. This keeps the later kebabs tasting clean rather than bitter.',
      'Rest the kebabs for three to five minutes. Serve with mint chutney, lemon and onion. For rolls, wrap them in warm paratha with yogurt, chutney and sliced salad.'
    ],idea:'Add a tiny amount of crushed dried fenugreek to the mince and keep fresh coriander dominant. The combination gives a warm, smoky aroma while still tasting recognisably Pakistani rather than like a generic kebab.',serve:'Serve with mint chutney, naan or paratha, sliced onion and lemon. They are excellent in a homemade seekh-kebab roll.',tips:['Kebab falling apart: squeeze onion drier and chill the mince longer.','Dry kebab: avoid overcooking and do not press repeatedly while grilling.','Too spicy: serve with plain yogurt and fresh salad rather than changing the whole batch.','Raw centre: cook over slightly lower heat after browning so the inside catches up.','Burnt exterior: reduce heat after the initial sear and turn more gently.']},
    'daal-makhani':{en:{title:'Daal Makhani',intro:'Slow, creamy daal makhani with black lentils, kidney beans and a deep tomato-butter finish. The texture comes from long gentle simmering and natural starch, not from large amounts of cream.',ingredients:['1 cup whole black urad dal','1/4 cup kidney beans','1 onion','2 tomatoes','1 tbsp ginger-garlic paste','1 tsp cumin','1 tsp chili powder','1/2 tsp garam masala','2 tbsp butter','2 tbsp cream','1 tbsp oil','Salt','Fresh coriander'],times:'Soak 8 hr • Cook 90 min+ • Finish 10 min',steps:[
      'Rinse the urad dal and kidney beans thoroughly and soak them separately or together for at least eight hours. Drain and rinse before cooking. A good soak shortens cooking time and helps the beans soften evenly.',
      'Pressure cook or simmer the soaked lentils with fresh water and a little salt until completely tender. They should crush easily between two fingers. If they still have a firm centre, keep cooking rather than trying to fix the texture later.',
      'Heat oil and half the butter in a heavy pot. Add cumin, then onion, and cook until golden. Stir in ginger-garlic paste and fry until the raw smell disappears without browning the garlic too deeply.',
      'Add chopped tomatoes, chili powder and salt. Cook until the tomato base is thick and the oil begins to separate. This slow bhunai is what keeps the finished dal from tasting like boiled lentils with cream added at the end.',
      'Add the cooked lentils and enough cooking liquid to create a loose curry. Simmer gently for 25–30 minutes, stirring occasionally. The beans release starch and the sauce becomes naturally creamy as it reduces.',
      'Mash a small portion of the lentils against the side of the pot. Keep most of the beans intact so the dish still has body. Add hot water if the dal becomes too tight during the long simmer.',
      'Add remaining butter, garam masala and cream during the final 5–10 minutes. Keep the heat low. Taste for salt and adjust before turning off the flame; dairy can soften the perception of seasoning.',
      'Rest for 10 minutes, then garnish with coriander and a small butter swirl. Serve hot. The dal will thicken further as it sits, so keep a little hot water available for reheating.'
    ],idea:'Finish with one spoon of the lentil cooking liquid mixed into the final butter. Spoon it over the surface just before serving; it gives the top a glossy dal aroma without making the whole pot heavy.',serve:'Serve with naan, tandoori roti, jeera rice or plain basmati rice. A sharp onion salad balances the richness.',tips:['Dal not creamy: simmer longer and mash a small portion.','Too thick: add hot water gradually.','Too watery: reduce uncovered on low heat.','Too rich: brighten with a small amount of lemon at serving rather than adding more cream.','Burnt base: transfer the upper dal to a clean pot without scraping the bottom.']},
    'chicken-pulao':{en:{title:'Chicken Pulao',intro:'A fragrant Pakistani chicken pulao where the rice cooks in a seasoned stock instead of a heavy masala. The result should be light, savoury and aromatic, with separate rice grains and tender chicken.',ingredients:['500 g chicken','2 cups basmati rice','1 onion','1 tbsp ginger-garlic paste','1 cinnamon stick','3 cardamom pods','4 cloves','1 bay leaf','1 tsp cumin','1/2 tsp black pepper','3.5 cups water or stock','2 tbsp oil','Salt','Fresh coriander'],times:'Prep 15 min • Cook 45 min • Rest 10 min',steps:[
      'Wash and soak the basmati rice for 20 minutes. Drain thoroughly. Measure the cooking liquid before the rice enters the pot because pulao depends on a controlled rice-to-liquid ratio.',
      'Heat oil and fry sliced onion until golden. Remove a little for garnish if desired. Add whole spices and cumin and let them sizzle briefly so their aroma moves into the oil.',
      'Add ginger-garlic paste and chicken. Brown lightly on all sides. You are building a savoury stock here, so do not rush this stage or leave the raw ginger-garlic smell behind.',
      'Add water or stock, salt and black pepper. Cover and simmer until the chicken is nearly tender and the liquid tastes well seasoned. The stock should taste slightly stronger than you want the final rice because the rice will absorb it.',
      'Add drained rice and stir once carefully so it is distributed evenly. Bring to a boil, then reduce the heat. Do not keep stirring once the rice starts absorbing the stock.',
      'Cook until most of the liquid disappears and small steam holes appear across the surface. Cover tightly and place on the lowest heat for 10–12 minutes to finish the grains with steam.',
      'Turn off the heat and rest the covered pot for another 10 minutes. This step matters: opening immediately releases steam and can leave the top grains undercooked.',
      'Fluff gently with a fork or flat spoon, lifting from the bottom. Taste for salt and garnish with fried onion and coriander. Serve immediately while the rice is light and fragrant.'
    ],idea:'Use a light chicken stock made from the same bones or skin trimmed from the chicken. It gives the rice deeper flavour without turning pulao into a spicy biryani.',serve:'Serve with raita, cucumber, salad and lemon. It is also excellent with a simple shorba on the side.',tips:['Rice mushy: reduce liquid next time and avoid stirring.','Rice hard: sprinkle a few tablespoons of hot water, cover and steam for five minutes.','Pulao bland: season the stock properly before adding rice.','Chicken dry: use bone-in pieces or stop cooking once tender.','Bottom browning too fast: use a tawa under the pot on the final steam.']},
    'butter-naan':{en:{title:'Butter Naan',intro:'Soft, lightly charred naan finished with butter, designed for a home tawa or very hot oven. A soft dough, proper resting time and strong initial heat matter more than complicated ingredients.',ingredients:['2 cups plain flour','1/2 tsp salt','1/2 tsp sugar','1/2 tsp baking powder','1/4 tsp baking soda','1/3 cup plain yogurt','1 tbsp oil','About 1/2 cup warm water','Butter for brushing','Coriander or nigella seeds, optional'],times:'Prep 15 min • Rest 60 min • Cook 15 min',steps:[
      'Mix flour, salt, sugar, baking powder and baking soda. Add yogurt and oil, then gradually add warm water. Knead into a soft, slightly tacky dough; do not make it stiff like roti dough.',
      'Knead for 5–7 minutes until the surface becomes smoother. Cover with a damp cloth and rest for at least 45–60 minutes. Resting relaxes the gluten so the naan stretches without fighting back.',
      'Divide into equal balls and lightly flour the work surface. Roll or stretch one ball into an oval. Keep the centre slightly thicker than the edges so the bread puffs without becoming brittle.',
      'Brush one side lightly with water if cooking on a tawa. Press optional seeds or coriander onto the dry side. The water helps the naan grip the hot surface; skip it only if your pan method requires otherwise.',
      'Place the wet side down on a very hot tawa. Within seconds bubbles should appear. Cover briefly or turn toward direct flame if using a suitable tawa method, taking care with heat and ventilation.',
      'Cook until browned spots develop and the centre is fully set. Avoid low heat because it dries the bread before it can puff. If using an oven, use a preheated high-temperature surface for the same reason.',
      'Remove and immediately brush with butter. Stack cooked naan under a clean cloth so the steam keeps them flexible rather than letting the surface dry.',
      'Serve hot with karahi, butter chicken, nihari or daal makhani. If the naan will sit for more than a few minutes, keep it wrapped so it stays soft.'
    ],idea:'Mix a pinch of crushed nigella seed with the butter used for brushing. The seeds stay aromatic on the hot naan and give a subtle bakery-style finish without changing the dough.',serve:'Best with karahi gosht, butter chicken, nihari or creamy dal. Serve straight from the tawa.',tips:['Naan hard: dough was too stiff or bread was cooked too long.','Naan not puffing: increase initial heat and rest the dough longer.','Burnt spots too quickly: reduce direct heat slightly after the first bubbles.','Dough sticky: dust lightly, but avoid adding lots of flour because it makes naan tough.','Dry after cooling: wrap in a clean cloth and reheat briefly with a little moisture.']},
    'aloo-gobi':{en:{title:'Aloo Gobi',intro:'Dry-style Indian aloo gobi with potatoes and cauliflower that are cooked through without turning into mash. The technique is simple: control moisture, use moderate heat and give the vegetables room to brown.',ingredients:['400 g cauliflower florets','300 g potatoes','1 onion','2 tomatoes','1 green chili','1 tsp cumin','1/2 tsp turmeric','1 tsp coriander powder','1/2 tsp chili powder','2 tbsp oil','Salt','Fresh coriander','1 tsp lemon juice'],times:'Prep 15 min • Cook 30–35 min • Rest 5 min',steps:[
      'Cut potatoes into similar pieces and cauliflower into medium florets. Rinse and dry them well. Surface water creates steam, which can make a dry aloo gobi watery and prevents the vegetables from developing roasted edges.',
      'Heat oil in a wide pan and add cumin. Add potatoes first because they usually need more time. Cook for several minutes, turning occasionally, until the edges begin to colour.',
      'Add cauliflower and cook uncovered for another 5–6 minutes. Keep the pan wide enough that the vegetables sit mostly in one layer. Overcrowding traps moisture and changes the dish from dry to stewed.',
      'Add onion, turmeric, coriander powder, chili powder and salt. Stir gently so the spices coat the vegetables without breaking the florets. Cook until the onion softens and the spices smell cooked rather than raw.',
      'Add tomatoes only when the vegetables have already taken some colour. Cook until the tomato softens. If your tomatoes release lots of water, keep the lid off and allow the moisture to evaporate.',
      'Cover for a short period, about 5–7 minutes, only if the potatoes remain firm. Check rather than assuming the full time is needed. The cauliflower should stay intact and the potato should be tender in the centre.',
      'Remove the lid and return to medium heat for a final drying stage. Taste and adjust salt. Add green chili and lemon near the end so their fresh flavour remains noticeable.',
      'Rest for five minutes and garnish with coriander. Serve as a side or with roti. Avoid vigorous stirring during the final stage because soft cauliflower breaks easily.'
    ],idea:'Brown the potato edges first and add the cauliflower after. This staggered cooking creates two textures in one pan: crisp-edged potato and tender, lightly roasted cauliflower.',serve:'Serve with roti, naan, dal and plain yogurt. It also works well as a filling for a simple paratha.',tips:['Vegetables mushy: reduce water and keep the lid off more often.','Potatoes hard: add a small splash of water and cover briefly.','Masala sticking: lower heat and add a tablespoon of water rather than scraping aggressively.','Too oily: use a wider pan so moisture evaporates efficiently instead of adding more oil.','Too salty: add a little extra cooked potato or serve with unsalted yogurt.']},
    'rajma-masala':{en:{title:'Rajma Masala',intro:'Comforting Indian rajma masala with tender kidney beans, a deeply cooked tomato-onion base and a naturally thick gravy. The beans are simmered long enough to absorb the masala instead of simply being coated on the surface.',ingredients:['3 cups cooked kidney beans','1 large onion','3 tomatoes','1 tbsp ginger-garlic paste','1 tsp cumin','1 tsp coriander powder','1/2 tsp turmeric','1 tsp chili powder','1/2 tsp garam masala','2 tbsp oil','Salt','Fresh coriander','1 tbsp lemon juice'],times:'Prep 15 min • Cook 35–45 min • Rest 5 min',steps:[
      'If using dried kidney beans, soak and cook them separately until completely tender before starting the curry. Undercooked kidney beans should not be used. If using cooked beans, rinse them and reserve some cooking liquid.',
      'Heat oil and cumin in a heavy pan. Add finely chopped onion and cook slowly until golden at the edges. This develops sweetness and creates a stronger foundation than lightly softened onion.',
      'Add ginger-garlic paste and cook for one minute. Add tomatoes, turmeric, coriander powder, chili powder and salt. Cook uncovered until the tomato mixture becomes thick and the oil begins to separate.',
      'Add a splash of bean cooking liquid and scrape the masala gently into a smooth base. This keeps the curry moist while the spices continue to cook without scorching.',
      'Add the kidney beans and enough liquid to create a medium-thick curry. Simmer for 15–20 minutes. Stir occasionally but do not crush every bean; keeping most of them whole gives the final dish better texture.',
      'Mash a small handful of beans against the side of the pan. Their starch thickens the gravy naturally. Continue simmering until the sauce coats the beans and a spoon dragged through the pan leaves a short trail.',
      'Add garam masala during the final few minutes. Taste for salt and acidity. Lemon should be added near the end so its brightness remains noticeable rather than disappearing into the long cook.',
      'Rest for five minutes before serving. The gravy will thicken slightly as it cools. If it becomes too tight, loosen each serving with a spoon of hot water rather than thinning the entire pot.'
    ],idea:'Keep one small cup of whole kidney beans aside, mash the rest of the beans lightly into the gravy, then fold the reserved whole beans back at the end. The contrast makes every bite feel richer and more deliberate.',serve:'Serve with basmati rice or jeera rice, sliced onion, yogurt and lemon. Rajma chawal is especially good when the curry has rested before serving.',tips:['Beans still firm: continue simmering with hot liquid; do not force them to soften with high heat.','Gravy thin: mash more beans and reduce uncovered.','Too salty: add unsalted beans or water and simmer briefly.','Too sour: cook the tomato base longer and balance carefully with a tiny pinch of sugar if needed.','Burnt masala: transfer the clean upper curry to another pan without scraping the bitter bottom.']},
    'kheer':{en:{title:'Kheer',intro:'Slow-cooked Pakistani-Indian rice kheer with creamy milk, tender rice, cardamom and a gentle sweetness. The secret is patience: reduce the milk gradually and stir the bottom often enough to prevent scorching.',ingredients:['1 litre full-fat milk','1/4 cup basmati rice','1/2 cup sugar, adjust to taste','4 cardamom pods','2 tbsp chopped almonds','2 tbsp pistachios','1 tbsp raisins','1 tsp rose water, optional'],times:'Prep 10 min • Cook 50–70 min • Chill 1 hr optional',steps:[
      'Rinse the rice and soak it for 15 minutes. Drain well. A small quantity of rice is enough because the grains expand and release starch during the long milk simmer.',
      'Bring the milk to a gentle boil in a heavy-bottomed pot. Lower the heat immediately. Stir the bottom and sides frequently, especially during the first 20 minutes, because milk solids can catch before the kheer visibly thickens.',
      'Crush the soaked rice lightly with your fingers or the back of a spoon and add it to the milk. This helps release starch and creates a creamy texture while still leaving small rice grains visible.',
      'Simmer uncovered on low heat, stirring every few minutes. Do not use a high flame to speed this up. The milk should reduce gradually and the rice should become completely tender without turning into a paste.',
      'Add crushed cardamom when the rice is nearly cooked. Keep simmering until the kheer coats the back of a spoon. Remember that it will thicken further after cooling, so do not reduce it until it looks solid in the hot pot.',
      'Add sugar and stir until fully dissolved. Sugar can be added earlier, but late addition makes it easier to judge sweetness and reduces the chance of excessive caramelisation on the bottom.',
      'Add nuts and raisins during the final few minutes. Turn off the heat and add rose water only if desired. Taste while warm and adjust sweetness carefully because chilled kheer tastes slightly less sweet.',
      'Serve warm or chill for at least one hour. Garnish with pistachio and almond slivers. If chilled kheer becomes too thick, loosen individual portions with a spoon of cold milk rather than adding a lot to the whole batch.'
    ],idea:'Toast only half the pistachios and keep the other half raw for garnish. The contrast between roasted nut aroma and fresh nut texture makes a simple kheer feel more layered.',serve:'Serve warm for a comforting dessert or chilled after a biryani, pulao or festive meal.',tips:['Kheer burnt: transfer the clean top to another pot without scraping the bottom.','Too thick: loosen with milk after cooling.','Too thin: continue low simmering; do not add flour or starch.','Rice still firm: continue cooking with a little warm milk.','Too sweet: add more unsweetened milk and simmer briefly.']},
    'chicken-handi':{en:{title:'Chicken Handi',intro:'Creamy Pakistani-style chicken handi with a tomato-onion base, yogurt, cream and a controlled finish of spices. The goal is a rich but balanced handi that tastes cooked from scratch rather than simply creamy.',ingredients:['600 g boneless chicken','1 medium onion','3 tomatoes','1/2 cup yogurt','1/3 cup cream','2 tbsp oil','1 tbsp ginger-garlic paste','1 tsp cumin','1 tsp coriander powder','1/2 tsp chili powder','1/2 tsp garam masala','1/2 tsp kasuri methi','Salt','Fresh coriander'],times:'Prep 15 min • Cook 35 min • Rest 5 min',steps:[
      'Cut chicken into even pieces and pat dry. Heat oil in a handi or heavy pan and sear the chicken in batches until lightly coloured. Remove it temporarily so the masala can cook without overcooking the meat.',
      'Add onion to the same pan and cook until soft and lightly golden. Stir in ginger-garlic paste and cumin. Fry just until fragrant; the base should smell warm and savoury, not burnt.',
      'Add tomatoes, coriander powder, chili powder and salt. Cook uncovered until the tomatoes collapse and the mixture becomes thick. If the pan dries before the tomato cooks, add a tablespoon of water at a time.',
      'Lower the heat and add yogurt gradually, stirring continuously so it blends into the tomato base instead of curdling. Cook until the sauce becomes smooth and the oil begins to appear around the edges.',
      'Return the chicken and any resting juices to the pan. Add a small splash of water, cover and simmer until the chicken is fully tender. Avoid a hard boil because it can make boneless chicken dry.',
      'Add cream, garam masala and crushed kasuri methi during the final 3–4 minutes. Keep the heat low. Taste before adding more salt because the cream softens the perception of seasoning.',
      'If the gravy is too thick, loosen with warm water or a little milk. If too thin, uncover and simmer gently. The finished sauce should cling to the chicken but still flow when spooned onto naan.',
      'Rest for five minutes and garnish with coriander. Serve hot from the handi. A small drizzle of cream is enough; too much will hide the tomato and spice character.'
    ],idea:'Crush kasuri methi between your palms and add it in two stages: a little while the cream simmers and a pinch after the heat is off. This gives both depth and a fresh aroma.',serve:'Serve with butter naan, tandoori roti, plain naan or basmati rice. Add onion and cucumber on the side for freshness.',tips:['Yogurt curdles: lower heat and add yogurt gradually while stirring.','Gravy thin: reduce uncovered after the chicken is cooked.','Chicken dry: use moderate heat and stop once tender.','Too rich: add a few drops of lemon or serve with fresh salad.','Burnt tomato base: transfer the clean upper sauce to a fresh pan and continue gently.']}
  };

  const U={
    biryani:{title:'چکن بریانی',intro:'خوشبودار پاکستانی اور بھارتی انداز کی چکن بریانی جس میں الگ الگ باسمتی چاول، اچھی طرح بھنا ہوا چکن مصالحہ اور ہلکی دم شامل ہے۔ اس ترکیب میں گھر کے باورچی خانے کے لیے مقدار، وقت، چاول کی ساخت اور ذائقے کا توازن واضح رکھا گیا ہے۔',ingredients:['500 گرام ہڈی والا چکن','2 کپ باسمتی چاول','1 بڑی پیاز باریک کٹی ہوئی','2 درمیانے ٹماٹر','1 کپ دہی','2 کھانے کے چمچ تیل','1 کھانے کا چمچ ادرک لہسن پیسٹ','1–2 کھانے کے چمچ بریانی مصالحہ','1 چائے کا چمچ زیرہ','1/2 چائے کا چمچ ہلدی','1/2 چائے کا چمچ لال مرچ','نمک حسب ذائقہ','1 ہری مرچ','آدھا کپ ہرا دھنیا اور پودینہ','1 کھانے کا چمچ لیموں'],times:'تیاری 25 منٹ • پکانے کا وقت 50 منٹ • دم کے بعد 5 منٹ',steps:['چاول کئی بار دھو کر پانی تقریباً صاف ہونے تک صاف کریں اور 20 منٹ بھگو دیں۔ پھر اچھی طرح نتھاریں۔ اس مختصر بھگونے سے دانے یکساں پکتے ہیں اور دم کے وقت ٹوٹتے نہیں۔','بھاری دیگچی میں تیل گرم کر کے پیاز کو آہستہ آہستہ گہرا سنہری کریں۔ تقریباً ایک تہائی پیاز نکال کر رکھیں۔ پیاز جلنے نہ دیں کیونکہ اس کی کڑواہٹ پوری بریانی کے ذائقے پر غالب آ سکتی ہے۔','ادرک لہسن اور چکن شامل کر کے درمیانی آنچ پر 6 سے 8 منٹ بھونیں۔ چکن کا رنگ بدل جائے اور کچا خوشبو ختم ہو جائے تو اگلے مرحلے پر جائیں۔','ٹماٹر، دہی، بریانی مصالحہ، زیرہ، ہلدی، لال مرچ اور نمک شامل کریں۔ کھلا پکا کر مصالحہ گاڑھا کریں۔ جب کناروں پر تیل نظر آئے تو سمجھیں کہ بھونائی مناسب ہو گئی ہے۔','نمک والے وافر پانی میں چاول تقریباً 80 فیصد گلنے تک ابالیں۔ دانے کے اندر ہلکی سختی باقی ہونی چاہیے۔ فوراً نتھار لیں تاکہ باقی پکنے کا عمل دم میں ہو۔','چاول کو چکن کے اوپر تہہ کی صورت میں پھیلائیں اور تلی ہوئی پیاز، پودینہ، دھنیا، ہری مرچ اور لیموں شامل کریں۔ سب کچھ فوراً مکس نہ کریں ورنہ چاول ٹوٹ سکتے ہیں۔','ڈھکن اچھی طرح بند کر کے بہت ہلکی آنچ پر تقریباً 15 منٹ دم دیں۔ اگر دیگچی پتلی ہو تو نیچے توا رکھیں۔ چولہا بند کر کے مزید 5 منٹ ڈھکن نہ کھولیں۔','چاول کو کناروں سے آہستہ اٹھا کر فلَف کریں۔ زیادہ مکس نہ کریں۔ ایک چاول اور چکن کا ٹکڑا چکھ کر آخر میں نمک یا لیموں کی معمولی درستگی کریں۔'],idea:'دم کے وقت چکن اور چاول کے درمیان تھوڑی سی کُٹی ہوئی خشک پودینہ ڈالیں۔ اس سے خوشبو تازہ اور مٹیالی رہتی ہے مگر بریانی پر پودینے کا ذائقہ حاوی نہیں ہوتا۔',serve:'ٹھنڈی رائتہ، کھیرا پیاز، لیموں اور ہلکی کچومر کے ساتھ گرم پیش کریں۔',tips:['چاول نرم ہو جائیں تو اگلی بار 80 فیصد پر فوراً نتھاریں۔','مصالحہ پتلا ہو تو چاول ڈالنے سے پہلے کھلا بھونیں۔','چکن خشک ہو تو اسے زیادہ تیز آنچ پر نہ پکائیں۔','نمک زیادہ ہو تو سادہ دہی اور کم نمک والی سلاد کے ساتھ پیش کریں۔','ذائقہ کم ہو تو چاول کے پانی اور چکن دونوں کو الگ الگ مناسب نمک دیں۔']},
    'karahi-gosht':{title:'کڑاہی گوشت',intro:'پاکستانی انداز کی کڑاہی جس میں گوشت، ٹماٹر اور مصالحے کو اچھی بھونائی کے ساتھ گاڑھا کیا جاتا ہے۔ آخر میں تازہ ادرک اور ہری مرچ شامل کرنے سے گہرے ٹماٹر مصالحے کے مقابل ایک تازہ خوشبو پیدا ہوتی ہے۔',ingredients:['750 گرام مٹن یا بیف','3 پکے ٹماٹر','1 درمیانی پیاز','3 کھانے کے چمچ تیل','1 کھانے کا چمچ ادرک لہسن','2 ہری مرچ','1 چائے کا چمچ زیرہ','1 چائے کا چمچ دھنیا پاؤڈر','1 چائے کا چمچ لال مرچ','1/2 چائے کا چمچ ہلدی','نمک','ہرا دھنیا','باریک کٹی ادرک'],times:'تیاری 15 منٹ • پکانا 60–75 منٹ • آرام 5 منٹ',steps:['گوشت خشک کر کے گرم کڑاہی میں تیل کے ساتھ اچھی طرح براون کریں۔ اگر ضرورت ہو تو گوشت دو حصوں میں پکائیں۔ زیادہ گوشت ایک ساتھ ڈالنے سے پانی نکلتا ہے اور براوننگ متاثر ہوتی ہے۔','پیاز، ادرک لہسن شامل کر کے نرم ہونے تک پکائیں۔ کچا پن ختم ہونے دیں لیکن لہسن کو نہ جلائیں کیونکہ لمبی پکائی میں جلی ہوئی خوشبو مزید نمایاں ہو جاتی ہے۔','ٹماٹر، زیرہ، دھنیا، لال مرچ، ہلدی اور نمک شامل کریں۔ ڈھک کر ٹماٹر نرم ہونے دیں اور کبھی کبھار ہلائیں تاکہ نیچے مصالحہ نہ لگے۔','گوشت نرم ہونے تک ہلکی آنچ پر پکائیں۔ ضرورت کے مطابق تھوڑا تھوڑا گرم پانی شامل کریں۔ مٹن کو عموماً کم وقت اور بیف کو زیادہ وقت لگ سکتا ہے، اس لیے نرمی کو اصل معیار بنائیں۔','گوشت گل جائے تو ڈھکن ہٹا کر درمیانی آنچ پر بھونیں۔ اضافی پانی خشک ہو اور مصالحہ چمکدار ہو کر گوشت سے لپٹ جائے۔','نمک اور مرچ چکھیں۔ اگر ٹماٹر بہت کھٹے ہوں تو معمولی سی چٹکی چینی ذائقہ متوازن کر سکتی ہے، مگر کڑاہی کا بنیادی ذائقہ نمکین اور تازہ رہنا چاہیے۔','آخر کے دو منٹ میں ہری مرچ اور آدھی ادرک ڈالیں۔ باقی ادرک آخر میں ڈالنے سے اس کی تازہ خوشبو محفوظ رہتی ہے۔','پانچ منٹ آرام دے کر دھنیا اور باقی ادرک ڈالیں۔ گرم نان یا روٹی کے ساتھ فوراً پیش کریں۔'],idea:'ہری مرچ اور ادرک کا بڑا حصہ آخر میں ڈالیں تاکہ بھنی ہوئی ٹماٹر گریوی کے اوپر تازہ خوشبو محسوس ہو۔ یہ عام کڑاہی کو ایک واضح پاکستانی گھر/ڈھابہ انداز دیتا ہے۔',serve:'نان، روٹی یا بٹر نان کے ساتھ پیاز، لیموں اور سادہ دہی پیش کریں۔',tips:['گوشت سخت ہو تو ہلکی آنچ پر مزید پکائیں۔','گریوی پتلی ہو تو کھول کر بھونیں۔','نیچے جل جائے تو اوپر والا صاف سالن دوسری دیگچی میں منتقل کریں اور جلی تہہ نہ کھرچیں۔','زیادہ کھٹا ہو تو معمولی چٹکی چینی کے بعد دو منٹ پکائیں۔','زیادہ تیل ہو تو آرام کے بعد صرف اوپر کا اضافی تیل نکالیں۔']},
    'daal-chawal':{title:'دال چاول',intro:'گھر کے روایتی پاکستانی انداز کے دال چاول جن میں نرم دال، خوشبودار تڑکا اور الگ الگ چاول شامل ہیں۔ دال اتنی گاڑھی ہونی چاہیے کہ چاول پر اچھی طرح بیٹھے لیکن پیسٹ جیسی نہ ہو۔',ingredients:['1 کپ مسور یا مونگ دال','1 کپ باسمتی چاول','1 چھوٹی پیاز','1 ٹماٹر','4 جوے لہسن','1 چائے کا چمچ زیرہ','1/2 چائے کا چمچ ہلدی','1/2 چائے کا چمچ لال مرچ','2 کھانے کے چمچ تیل یا گھی','نمک','ہرا دھنیا','1 ہری مرچ'],times:'تیاری 10 منٹ • پکانا 35–40 منٹ • آرام 5 منٹ',steps:['دال اچھی طرح دھو کر کسی کنکر کو نکال دیں۔ 15 سے 20 منٹ بھگونا اختیاری ہے لیکن پرانی دال کے لیے فائدہ مند ہے۔','دال کو پانی، ہلدی اور تھوڑے نمک کے ساتھ نرم ہونے تک پکائیں۔ چمچ کے پچھلے حصے سے دال آسانی سے ٹوٹ جائے تو ساخت درست ہے۔','چاول الگ برتن میں نمک والے پانی میں پکائیں۔ دانہ نرم ہو مگر چپچپا نہ ہو۔ نتھارنے کے بعد پانچ منٹ ڈھک کر رکھیں اور پھر ہلکے ہاتھ سے کھولیں۔','تڑکے کے لیے تیل یا گھی گرم کریں۔ زیرہ، لہسن اور پیاز ڈالیں اور ہلکا سنہری ہونے دیں۔ ٹماٹر، لال مرچ اور ہری مرچ شامل کر کے ٹماٹر نرم کریں۔','پکی ہوئی دال کو ہلکا پھینٹیں۔ اگر بہت گاڑھی ہو تو گرم پانی تھوڑا تھوڑا شامل کریں۔ اگر پتلی ہو تو بغیر ڈھکن کے چند منٹ پکائیں۔','گرم تڑکا دال پر ڈالیں۔ تھوڑا تڑکا اوپر کے لیے بچایا جا سکتا ہے۔ تڑکا شامل ہونے کے بعد نمک دوبارہ چکھیں کیونکہ ذائقہ اب مکمل ہو رہا ہے۔','پانچ منٹ آرام دیں تاکہ تڑکے کی خوشبو دال میں شامل ہو۔ چاول کو کانٹے یا چپٹے چمچ سے ہلکا سا فلَف کریں۔','چاول پلیٹ میں رکھ کر ایک طرف دال ڈالیں۔ اوپر دھنیا، ہری مرچ اور حسب ذائقہ لیموں دیں۔ سادہ دہی بھی ساتھ رکھا جا سکتا ہے۔'],idea:'ہر پلیٹ پر زیرہ، لہسن اور تھوڑے گھی کا ایک چھوٹا تازہ تڑکا ڈالیں۔ اس سے دال کے پورے برتن کو زیادہ تیل دار کیے بغیر ہر serving میں خوشبو کا نیا مرحلہ آتا ہے۔',serve:'باسمتی چاول، پیاز، لیموں، ہری مرچ، دہی اور آم کے اچار کے ساتھ پیش کریں۔',tips:['دال گاڑھی ہو تو گرم پانی دیں۔','دال پتلی ہو تو کھلی پکائیں۔','تڑکا جل جائے تو نیا تڑکا بنائیں۔','چاول چپچپے ہوں تو اگلی بار زیادہ اچھی طرح دھوئیں اور زیادہ نہ پکائیں۔','ذائقہ پھیکا ہو تو پہلے نمک چیک کریں پھر لیموں شامل کریں۔']},
    nihari:{title:'نہاری',intro:'روایتی پاکستانی نہاری جس میں گوشت آہستہ پک کر نرم ہوتا ہے اور مصالحے دار شوربہ ہلکا گاڑھا کیا جاتا ہے۔ آخری مرحلے میں ادرک، ہری مرچ اور لیموں کی تازگی بھاری سالن کو متوازن کرتی ہے۔',ingredients:['750 گرام بیف شینک یا اسٹو گوشت','2 کھانے کے چمچ تیل یا گھی','1 بڑی پیاز','1 کھانے کا چمچ ادرک لہسن','2 کھانے کے چمچ نہاری مصالحہ','1/2 چائے کا چمچ لال مرچ','1/4 چائے کا چمچ ہلدی','2 کھانے کے چمچ گندم کا آٹا','6 کپ گرم پانی','نمک','ادرک، ہری مرچ، دھنیا، لیموں'],times:'تیاری 20 منٹ • پکانا 2–2.5 گھنٹے • آرام 10 منٹ',steps:['گوشت کے صرف زائد چربی والے حصے تراشیں اور بڑے ٹکڑے رکھیں۔ گرم تیل میں گوشت براون کریں تاکہ شوربے کی بنیاد گہری ہو۔','پیاز سنہری کریں اور ادرک لہسن شامل کریں۔ درمیانی آنچ رکھیں تاکہ پیاز یا لہسن نہ جلے۔','نہاری مصالحہ، لال مرچ، ہلدی اور نمک شامل کریں۔ 30 سے 40 سیکنڈ بھون کر گرم پانی ڈالیں اور نیچے لگی بھوری تہہ کو نرمی سے مصالحے میں شامل کریں۔','ڈھک کر بہت ہلکی آنچ پر گوشت نرم ہونے تک پکائیں۔ ضرورت ہو تو گرم پانی دیں۔ گوشت کانٹے سے آسانی سے ٹوٹنے لگے تو اگلا مرحلہ کریں۔','آٹے کو الگ ٹھنڈے پانی میں اچھی طرح گھولیں اور پتلی دھار میں شامل کریں۔ ساتھ مسلسل ہلاتے رہیں تاکہ گٹھلیاں نہ بنیں۔','10 سے 15 منٹ کھلا پکا کر گاڑھا پن چیک کریں۔ شوربہ چمچ پر ہلکی تہہ بنائے مگر ڈالنے کے قابل رہے۔','چولہا بند کر کے 10 منٹ آرام دیں۔ پھر نمک چکھیں کیونکہ آرام کے بعد مصالحے اور نمک کا توازن زیادہ واضح ہوتا ہے۔','گرم پیالے میں تازہ ادرک، دھنیا، ہری مرچ اور لیموں کے ساتھ پیش کریں۔ گارنش اختیاری نہیں بلکہ نہاری کی بھاری ساخت کو تازہ کرنے کا اہم حصہ ہے۔'],idea:'تازہ ادرک کو ایک منٹ ہلکے تیل میں گرم کر کے معمولی سا ادرک والا تیل بنائیں اور ہر پیالے پر چند قطرے ڈالیں۔ اس سے خوشبو بڑھتی ہے مگر سالن کی بنیادی ساخت نہیں بدلتی۔',serve:'نان یا خمیری روٹی کے ساتھ ادرک، دھنیا، ہری مرچ اور لیموں زیادہ مقدار میں پیش کریں۔',tips:['بہت گاڑھی ہو تو گرم پانی دیں۔','پتلی ہو تو کھلی پکائیں، مزید آٹا فوراً نہ ڈالیں۔','گوشت سخت ہو تو ہلکی آنچ پر مزید پکائیں۔','نمک زیادہ ہو تو بغیر نمک پانی یا شوربہ شامل کریں۔','نیچے جل جائے تو اوپر والا صاف سالن دوسری دیگچی میں منتقل کریں۔']},
    'palak-paneer':{title:'پالک پنیر',intro:'تازہ پالک، نرم پنیر اور ہلکے مصالحوں سے تیار ہونے والی بھارتی طرز کی پالک پنیر۔ پالک کو زیادہ دیر ابالنے کے بجائے مختصر blanch کر کے فوراً ٹھنڈا کیا جاتا ہے تاکہ رنگ اور تازہ ذائقہ بہتر رہے۔',ingredients:['500 گرام تازہ پالک','300 گرام پنیر','1 چھوٹی پیاز','2 ٹماٹر','1 کھانے کا چمچ ادرک لہسن','1 ہری مرچ','1 چائے کا چمچ زیرہ','1/2 چائے کا چمچ ہلدی','1 چائے کا چمچ دھنیا پاؤڈر','1/2 چائے کا چمچ گرم مصالحہ','2 کھانے کے چمچ تیل','2 کھانے کے چمچ کریم','نمک','1 چائے کا چمچ لیموں'],times:'تیاری 15 منٹ • پکانا 25 منٹ • آرام 5 منٹ',steps:['پالک اچھی طرح دھو کر موٹے ڈنٹھل نکالیں۔ ابلتے پانی میں تقریباً دو منٹ blanch کریں اور فوراً ٹھنڈے پانی میں ڈالیں۔ اس سے رنگ بہتر رہتا ہے اور مزید پکنے کا عمل رک جاتا ہے۔','پالک کو ہری مرچ اور تھوڑے پانی کے ساتھ نرم پیسٹ بنائیں۔ اگر texture پسند ہو تو تھوڑی پالک باریک کٹی ہوئی بھی چھوڑ سکتے ہیں۔','پنیر کے ٹکڑوں کو معمولی تیل میں ہلکا سنہری کریں۔ زیادہ نہ تلیں کیونکہ سخت پنیر بعد میں گریوی میں بھی ربڑ جیسا ہو سکتا ہے۔','دوسرے پین میں زیرہ، پیاز اور ادرک لہسن بھونیں۔ ٹماٹر، ہلدی اور دھنیا پاؤڈر شامل کریں اور ٹماٹر نرم ہونے تک پکائیں۔','ٹماٹر کا base گاڑھا ہو جائے اور کناروں پر تیل نظر آئے تو پالک پیسٹ شامل کریں۔ 5 سے 7 منٹ ہلکی آنچ پر پکائیں۔','پنیر، گرم مصالحہ، نمک اور کریم شامل کریں۔ مزید 3 سے 4 منٹ ہلکی آنچ پر رکھیں تاکہ پنیر گرم ہو اور گریوی کا ذائقہ جذب کرے۔','آخر میں لیموں شامل کریں۔ اگر گریوی بہت گاڑھی ہو تو نیم گرم پانی یا تھوڑا دودھ دیں۔ اگر پتلی ہو تو چند منٹ بغیر ڈھکن پکائیں۔','پانچ منٹ آرام دے کر نان، روٹی یا جیرا رائس کے ساتھ پیش کریں۔'],idea:'ہلکے سنہری پنیر کا ایک چھوٹا ٹکڑا گریوی میں پیس کر شامل کریں۔ اس سے قدرتی dairy body اور ہلکی roasted خوشبو آتی ہے، بغیر کسی آٹے کے۔',serve:'نان، روٹی، جیرا رائس یا سادہ باسمتی چاول کے ساتھ پیش کریں۔',tips:['پالک کا رنگ مدھم ہو تو اسے زیادہ دیر نہ ابالیں۔','پنیر سخت ہو تو اسے زیادہ نہ تلیں۔','گریوی گاڑھی ہو تو گرم پانی یا دودھ دیں۔','پتلی ہو تو ہلکی آنچ پر کھلی پکائیں۔','کڑوا ذائقہ ہو تو نمک، کریم اور معمولی لیموں سے balance کریں۔']}
  };

  // For Urdu recipes not listed above, use the existing Urdu titles/images but enrich their method and tips with a controlled, recipe-specific framework.
  const fallback={
    'butter-chicken':{title:'بٹر چکن',i:'کریمی ٹماٹر گریوی میں نرم چکن، مکھن، دہی اور کریم سے تیار ہونے والی خوشبودار ڈش۔',a:['600 گرام چکن','آدھا کپ دہی','3 ٹماٹر','1 کھانے کا چمچ ادرک لہسن','2 کھانے کے چمچ مکھن','آدھا کپ کریم','گرم مصالحہ','نمک'],s:['چکن کو دہی، لیموں، ادرک لہسن اور مصالحوں میں کم از کم 30 منٹ میرینیٹ کریں۔','تیز گرم پین میں چکن کو بیچز میں ہلکا براون کریں تاکہ سطح پر رنگ آئے مگر اندر خشک نہ ہو۔','ٹماٹر کی گریوی کو الگ پکا کر خام بو ختم کریں اور ضرورت ہو تو بلینڈ کر کے ہموار کریں۔','چکن کو گریوی میں شامل کر کے ہلکی آنچ پر 8 سے 10 منٹ پکائیں۔','آخر میں مکھن، کریم اور کُٹی ہوئی کسوری میتھی شامل کریں اور پانچ منٹ آرام دیں۔'],idea:'کسوری میتھی کا آدھا حصہ پکاتے وقت اور آدھا چولہا بند کرنے کے بعد شامل کریں تاکہ خوشبو دو مرحلوں میں محسوس ہو۔',serve:'بٹر نان یا باسمتی چاول کے ساتھ گرم پیش کریں۔',tips:['گریوی کھٹی ہو تو مزید کریم یا معمولی چینی دیں۔','چکن خشک ہو تو پہلے مرحلے میں زیادہ نہ پکائیں۔','گریوی گاڑھی ہو تو گرم پانی دیں۔']},
    'chicken-tikka':{title:'چکن تکہ',i:'دہی اور مصالحوں میں میرینیٹ کیا ہوا رسیلا چکن تکہ جو تیز آنچ پر پک کر کناروں سے ہلکا smoky بنتا ہے۔',a:['600 گرام چکن','آدھا کپ گاڑھا دہی','1 کھانے کا چمچ لیموں','1 کھانے کا چمچ ادرک لہسن','تکہ مصالحہ','1 کھانے کا چمچ بیسن','نمک','تیل'],s:['چکن کو برابر ٹکڑوں میں کاٹ کر خشک کریں اور دہی، لیموں، ادرک لہسن، مصالحہ، بیسن اور نمک سے کوٹ کریں۔','کم از کم دو گھنٹے فریج میں میرینیٹ کریں۔','سیخوں پر چھوٹے gaps کے ساتھ لگائیں تاکہ گرم ہوا ہر طرف پہنچ سکے۔','اوون، گرل یا ایئر فرائر میں تیز آنچ پر پکائیں اور ایک دو بار پلٹیں۔','پانچ منٹ آرام دے کر لیموں، پیاز اور پودینے کی چٹنی کے ساتھ پیش کریں۔'],idea:'میرینیڈ میں تھوڑا roasted بیسن شامل کریں۔ یہ مصالحہ چکن پر باریک تہہ بناتا ہے، اچھی browning دیتا ہے اور texture کو خشک کیے بغیر خوشبو بڑھاتا ہے۔',serve:'پودینے کی چٹنی، پیاز، لیموں اور گرم نان کے ساتھ پیش کریں۔',tips:['میرینیڈ پھسلے تو دہی زیادہ پتلا نہ رکھیں۔','چکن خشک ہو تو کم وقت پکائیں۔','باہر زیادہ جل جائے تو آخری مرحلے میں heat کم کریں۔']},
    'gulab-jamun':{title:'گلاب جامن',i:'نرم گلاب جامن جو دودھ پاؤڈر کے ہلکے آٹے سے بن کر خوشبودار چینی کے شیرے میں جذب ہوتے ہیں۔',a:['1 کپ ملک پاؤڈر','3 کھانے کے چمچ میدہ','1/2 چائے کا چمچ بیکنگ پاؤڈر','2 کھانے کے چمچ گھی','دودھ حسب ضرورت','ڈیڑھ کپ چینی','ڈیڑھ کپ پانی','الائچی'],s:['چینی، پانی اور الائچی کا ہلکا شیرہ پہلے تیار کریں تاکہ جامن تلنے کے وقت گرم رہے۔','ملک پاؤڈر، میدہ اور بیکنگ پاؤڈر میں گھی ملائیں اور دودھ تھوڑا تھوڑا ڈال کر نرم آٹا بنائیں۔','چھوٹی بالز بناتے وقت سطح بالکل ہموار رکھیں تاکہ تلتے وقت cracks نہ ہوں۔','ہلکی آنچ پر جامن سنہری ہونے تک تلیں۔ تیز آنچ باہر سے جلا دے گی اور اندر کچا رہ سکتا ہے۔','گرم جامن کو گرم شیرے میں کم از کم ایک گھنٹہ بھگونے دیں اور پھر پستہ کے ساتھ پیش کریں۔'],idea:'آٹے میں ایک چٹکی پسی ہوئی الائچی بھی شامل کریں تاکہ خوشبو صرف شیرے کی سطح پر نہیں بلکہ جامن کے اندر بھی محسوس ہو۔',serve:'گرم یا نیم گرم شیرے کے ساتھ پستہ چھڑک کر پیش کریں۔',tips:['جامن پھٹیں تو آٹا خشک ہے؛ چند قطرے دودھ دیں۔','باہر جلدی بھورے ہوں تو آنچ کم کریں۔','شیرہ بہت گاڑھا ہو تو تھوڑا گرم پانی شامل کریں۔']},
    'chana-masala':{title:'چنا مصالحہ',i:'چنے، ٹماٹر، پیاز اور خوشبودار مصالحوں سے تیار ہونے والا گاڑھا بھارتی چنا مصالحہ۔',a:['3 کپ ابلے چنے','1 بڑی پیاز','3 ٹماٹر','ادرک لہسن','چنا مصالحہ','زیرہ','ہلدی','لال مرچ','تیل','نمک'],s:['تیل میں زیرہ اور پیاز کو سنہری کریں۔','ادرک لہسن، ٹماٹر اور خشک مصالحے ڈال کر ٹماٹر کا پانی کم ہونے تک بھونیں۔','ابلے چنے شامل کر کے تھوڑا پانی ڈالیں اور 15 منٹ ہلکی آنچ پر پکائیں۔','چند چنے چمچ سے میش کر کے گریوی کو قدرتی طور پر گاڑھا کریں۔','آخر میں لیموں اور دھنیا ڈال کر پانچ منٹ آرام دیں اور نان یا چاول کے ساتھ پیش کریں۔'],idea:'چند چنے میش کر کے دوبارہ گریوی میں ملانے سے بغیر آٹے یا کریم کے قدرتی thick texture ملتا ہے۔',serve:'نان، بھٹورا، پوری یا باسمتی چاول کے ساتھ پیاز اور لیموں پیش کریں۔',tips:['گریوی پتلی ہو تو چنے میش کریں۔','چنے سخت ہوں تو گرم پانی کے ساتھ مزید پکائیں۔','زیادہ کھٹاس ہو تو ٹماٹر کو مزید بھونیں۔']},
    'seekh-kebab':{title:'سیخ کباب',i:'پاکستانی انداز کے رسیلے سیخ کباب جن میں قیمہ، ہری مرچ، دھنیا اور گرم مصالحے کا متوازن ذائقہ ہوتا ہے۔',a:['500 گرام قیمہ','1 چھوٹی پیاز','2 ہری مرچ','ہرا دھنیا','ادرک لہسن','زیرہ','دھنیا پاؤڈر','لال مرچ','گرم مصالحہ','لیموں','نمک'],s:['پیاز کو بہت باریک کاٹ کر کپڑے میں زور سے نچوڑیں تاکہ اضافی پانی نکل جائے۔','قیمہ اور تمام مصالحے اچھی طرح ملا کر چند منٹ گوندھیں یہاں تک کہ mixture ہلکا sticky ہو جائے۔','30 منٹ فریج میں رکھیں تاکہ شکل بنانا آسان ہو۔','گیلے ہاتھ سے سیخ پر برابر موٹائی میں قیمہ لگائیں۔','گرم گرل یا پین پر پہلے سطح کو set ہونے دیں، پھر آہستہ پلٹ کر مکمل پکائیں۔','تین سے پانچ منٹ آرام دے کر نان، پیاز، لیموں اور پودینے کی چٹنی کے ساتھ پیش کریں۔'],idea:'قیمے میں ایک چٹکی کُٹی ہوئی کسوری میتھی شامل کریں اور تازہ دھنیا زیادہ رکھیں۔ اس سے دھواں دار خوشبو آتی ہے مگر کباب کا پاکستانی character برقرار رہتا ہے۔',serve:'نان یا گرم پراٹھے، پودینے کی چٹنی، پیاز اور لیموں کے ساتھ پیش کریں۔',tips:['کباب ٹوٹے تو پیاز زیادہ گیلی ہے؛ اسے مزید نچوڑیں۔','خشک ہوں تو زیادہ نہ پکائیں اور بار بار نہ دبائیں۔','اندر کچے ہوں تو heat تھوڑی کم کر کے مزید پکائیں۔']},
    'daal-makhani':{title:'دال مکھنی',i:'کالی دال اور راجما کو آہستہ پکانے سے بننے والی کریمی دال مکھنی جس میں مکھن اور کسوری میتھی کا متوازن اختتام ہے۔',a:['1 کپ ثابت اُڑد دال','1/4 کپ راجما','1 پیاز','2 ٹماٹر','ادرک لہسن','زیرہ','لال مرچ','مکھن','کریم','نمک'],s:['دال اور راجما کم از کم آٹھ گھنٹے بھگو کر اچھی طرح نرم ہونے تک پکائیں۔','مکھن اور تیل میں زیرہ، پیاز اور ادرک لہسن بھونیں۔','ٹماٹر، لال مرچ اور نمک شامل کر کے مصالحہ گاڑھا ہونے تک پکائیں۔','پکی دال شامل کر کے 25 سے 30 منٹ ہلکی آنچ پر simmer کریں۔','چند چمچ دال میش کر کے گریوی کو قدرتی طور پر creamy بنائیں۔','آخر میں مکھن، گرم مصالحہ، کریم اور کسوری میتھی ڈال کر دس منٹ آرام دیں۔'],idea:'دال کے cooking liquid کا ایک چمچ آخری مکھن میں ملا کر سطح پر ڈالیں۔ اس سے اوپر glossy اور خوشبودار finish آتی ہے۔',serve:'نان، تندوری روٹی یا جیرا رائس کے ساتھ پیش کریں۔',tips:['دال کریمی نہ ہو تو مزید simmer اور تھوڑی mash کریں۔','زیادہ گاڑھی ہو تو گرم پانی دیں۔','بہت rich ہو تو serving پر معمولی لیموں شامل کریں۔']},
    'chicken-pulao':{title:'چکن پلاؤ',i:'ہلکا اور خوشبودار پاکستانی چکن پلاؤ جس میں چاول مصالحہ دار شوربے میں پکتے ہیں اور بھاری ٹماٹر گریوی استعمال نہیں ہوتی۔',a:['500 گرام چکن','2 کپ باسمتی چاول','1 پیاز','ادرک لہسن','دار چینی','الائچی','لونگ','تیز پات','زیرہ','کالی مرچ','ساڑھے 3 کپ پانی یا اسٹاک','تیل','نمک'],s:['چاول دھو کر 20 منٹ بھگوئیں اور اچھی طرح نتھاریں۔','تیل میں پیاز سنہری کریں، ثابت مصالحے اور زیرہ ڈال کر خوشبو نکالیں۔','ادرک لہسن اور چکن شامل کر کے ہلکا براون کریں۔','پانی یا اسٹاک، نمک اور کالی مرچ ڈال کر چکن تقریباً گلنے تک پکائیں۔','چاول شامل کر کے ایک بار ہلائیں اور ابال آنے کے بعد آنچ کم کریں۔','پانی کم ہونے پر ڈھکن بند کر کے 10 سے 12 منٹ دم دیں۔','چولہا بند کر کے مزید 10 منٹ ڈھکن نہ کھولیں۔','کانٹے سے ہلکا فلَف کر کے تلی پیاز اور دھنیا کے ساتھ پیش کریں۔'],idea:'اسی چکن کی ہڈیوں سے ہلکا stock بنا کر استعمال کریں۔ اس سے پلاؤ کا ذائقہ گہرا ہوتا ہے مگر بریانی جیسا heavy نہیں ہوتا۔',serve:'رائتہ، کھیرا، سلاد اور لیموں کے ساتھ پیش کریں۔',tips:['چاول نرم ہوں تو liquid کم کریں۔','سخت ہوں تو چند چمچ گرم پانی دے کر دوبارہ دم دیں۔','پلاؤ پھیکا ہو تو stock میں نمک پہلے درست کریں۔']},
    'butter-naan':{title:'بٹر نان',i:'نرم، ہلکا چاربن والا نان جو گرم توا یا تیز گرم اوون میں تیار کر کے آخر میں مکھن سے finish کیا جاتا ہے۔',a:['2 کپ میدہ','1/2 چائے کا چمچ نمک','1/2 چائے کا چمچ چینی','بیکنگ پاؤڈر','بیکنگ سوڈا','1/3 کپ دہی','1 کھانے کا چمچ تیل','نیم گرم پانی','مکھن'],s:['میدہ، نمک، چینی، بیکنگ پاؤڈر اور سوڈا ملائیں۔ دہی اور تیل شامل کر کے نیم گرم پانی سے نرم ہلکا چپچپا آٹا بنائیں۔','5 سے 7 منٹ گوندھیں اور 45 سے 60 منٹ ڈھانپ کر آرام دیں۔','برابر بالز بنا کر oval شکل میں پھیلائیں؛ کنارے بہت پتلے نہ کریں۔','اگر توا استعمال ہو تو ایک طرف ہلکا پانی لگائیں تاکہ نان گرم سطح پر grip کرے۔','بہت گرم توا پر نان رکھیں اور bubbles آنے دیں۔','درمیانی سے تیز حرارت پر spots آنے تک پکائیں اور فوراً مکھن لگائیں۔','پکے نان کو صاف کپڑے میں ڈھانپیں تاکہ steam نرمی برقرار رکھے۔','گرم گرم کڑاہی، بٹر چکن یا دال مکھنی کے ساتھ پیش کریں۔'],idea:'مکھن میں ایک چٹکی کُٹی کلونجی ملا کر نان پر لگائیں۔ اس سے سادہ نان میں بیکری جیسی خوشبو آتی ہے۔',serve:'کڑاہی، بٹر چکن، نہاری یا دال مکھنی کے ساتھ گرم پیش کریں۔',tips:['نان سخت ہو تو آٹا زیادہ سخت یا cooking زیادہ ہوئی ہے۔','پھول نہ رہا ہو تو heat بڑھائیں اور dough کو زیادہ آرام دیں۔','جلد جل رہا ہو تو آخری heat کم کریں۔']},
    'aloo-gobi':{title:'آلو گوبھی',i:'خشک انداز کی آلو گوبھی جس میں آلو نرم اور کناروں سے ہلکے براون جبکہ گوبھی اپنی شکل برقرار رکھتی ہے۔',a:['400 گرام گوبھی','300 گرام آلو','1 پیاز','2 ٹماٹر','1 ہری مرچ','زیرہ','ہلدی','دھنیا پاؤڈر','لال مرچ','تیل','نمک','ہرا دھنیا'],s:['آلو اور گوبھی برابر سائز کے ٹکڑوں میں کاٹ کر اچھی طرح خشک کریں۔','تیل اور زیرے میں آلو پہلے ڈالیں اور کنارے رنگ پکڑنے تک پکائیں۔','گوبھی شامل کر کے کھلا مزید چند منٹ پکائیں تاکہ steam جمع نہ ہو۔','پیاز اور خشک مصالحے ڈال کر آہستہ ہلائیں۔','ٹماٹر آخر میں شامل کریں اور پانی زیادہ نکلے تو ڈھکن نہ لگائیں۔','اگر آلو سخت ہوں تو صرف 5 سے 7 منٹ مختصر ڈھکیں۔','آخر میں ڈھکن ہٹا کر excess moisture خشک کریں اور لیموں شامل کریں۔','پانچ منٹ آرام دے کر دھنیا کے ساتھ روٹی یا نان پر پیش کریں۔'],idea:'آلو کو پہلے براون اور گوبھی کو بعد میں شامل کریں۔ اس staggered cooking سے آلو کے کنارے crisp اور گوبھی tender رہتی ہے۔',serve:'روٹی، نان، دال اور دہی کے ساتھ پیش کریں۔',tips:['سبزی نرم ہو تو پانی کم رکھیں۔','آلو سخت ہوں تو تھوڑا پانی دے کر مختصر ڈھکیں۔','مصالحہ لگے تو heat کم کر کے ایک چمچ پانی دیں۔']},
    'rajma-masala':{title:'راجما مصالحہ',i:'نرم راجما، پیاز ٹماٹر کی بھنی ہوئی گریوی اور گرم مصالحے سے تیار ہونے والا گاڑھا بھارتی راجما۔',a:['3 کپ پکا ہوا راجما','1 بڑی پیاز','3 ٹماٹر','ادرک لہسن','زیرہ','دھنیا پاؤڈر','ہلدی','لال مرچ','گرم مصالحہ','تیل','نمک'],s:['اگر خشک راجما استعمال کریں تو پہلے مکمل نرم ہونے تک الگ پکائیں۔ کچا یا سخت راجما استعمال نہ کریں۔','تیل اور زیرے میں پیاز کو سنہری کریں۔','ادرک لہسن، ٹماٹر اور مصالحے ڈال کر کھلا بھونیں یہاں تک کہ تیل الگ ہونے لگے۔','تھوڑا راجما کا پانی ڈال کر مصالحے کو smooth base بنائیں۔','راجما شامل کر کے 15 سے 20 منٹ ہلکی آنچ پر simmer کریں۔','چند دانے دیگچی کے کنارے سے میش کریں تاکہ گریوی قدرتی طور پر گاڑھی ہو۔','آخر میں گرم مصالحہ، نمک اور لیموں شامل کریں۔','پانچ منٹ آرام دے کر چاول، دہی اور پیاز کے ساتھ پیش کریں۔'],idea:'زیادہ تر راجما ہلکا میش کر کے آخر میں چند دانے پورے واپس شامل کریں۔ اس سے گریوی creamy اور ہر نوالے میں whole beans کا اچھا contrast رہتا ہے۔',serve:'باسمتی یا جیرا رائس، پیاز، دہی اور لیموں کے ساتھ پیش کریں۔',tips:['گریوی پتلی ہو تو beans mash کریں۔','راجما سخت ہو تو مزید simmer کریں۔','کھٹا زیادہ ہو تو ٹماٹر base مزید پکائیں۔']},
    kheer:{title:'کھیر',i:'دودھ، چاول، الائچی اور خشک میوہ جات سے تیار ہونے والی پاکستانی و بھارتی انداز کی کریمی کھیر۔ اصل راز آہستہ reduction اور نیچے لگنے سے بچانے کے لیے مناسب stirring ہے۔',a:['1 لیٹر full-fat دودھ','1/4 کپ باسمتی چاول','1/2 کپ چینی','4 الائچی','بادام','پستہ','کشمش','عرق گلاب اختیاری'],s:['چاول دھو کر 15 منٹ بھگوئیں اور نتھاریں۔','بھاری برتن میں دودھ کو ابال کر فوراً آنچ ہلکی کریں۔','چاول شامل کر کے آہستہ آہستہ پکائیں اور ہر چند منٹ بعد نیچے چمچ چلائیں۔','دودھ کم ہوتے وقت آنچ تیز نہ کریں کیونکہ نیچے milk solids جل سکتے ہیں۔','الائچی اور نرم چاول کے بعد چینی شامل کریں اور مکمل گھلنے دیں۔','آخر میں بادام، پستہ اور کشمش ڈالیں۔','چولہا بند کر کے عرق گلاب ڈالیں اور گرم یا ٹھنڈی پیش کریں۔','ٹھنڈا ہونے پر اگر بہت گاڑھی ہو تو serving میں تھوڑا ٹھنڈا دودھ ملا سکتے ہیں۔'],idea:'آدھا پستہ ہلکا toast کریں اور آدھا تازہ garnish کے لیے رکھیں۔ roasted خوشبو اور fresh texture مل کر سادہ کھیر کو زیادہ layered بناتے ہیں۔',serve:'گرم یا ٹھنڈی، پستہ اور بادام کے ساتھ پیش کریں۔',tips:['نیچے لگ جائے تو اوپر کی صاف کھیر دوسرے برتن میں منتقل کریں۔','بہت گاڑھی ہو تو دودھ دیں۔','پتلی ہو تو low simmer جاری رکھیں۔']},
    'chicken-handi':{title:'چکن ہانڈی',i:'کریمی پاکستانی انداز کی چکن ہانڈی جس میں ٹماٹر، دہی، کریم اور مصالحوں کو الگ الگ مرحلوں میں پکا کر متوازن گریوی بنائی جاتی ہے۔',a:['600 گرام چکن','1 پیاز','3 ٹماٹر','1/2 کپ دہی','1/3 کپ کریم','2 کھانے کے چمچ تیل','ادرک لہسن','زیرہ','دھنیا پاؤڈر','لال مرچ','گرم مصالحہ','کسوری میتھی','نمک'],s:['چکن کو خشک کر کے تیل میں بیچز میں ہلکا براون کریں اور نکال لیں۔','اسی برتن میں پیاز، زیرہ اور ادرک لہسن کو خوشبودار ہونے تک پکائیں۔','ٹماٹر اور خشک مصالحے ڈال کر گاڑھا base بنائیں۔','آنچ کم کر کے دہی تھوڑا تھوڑا شامل کریں اور مسلسل ہلاتے رہیں تاکہ curdling نہ ہو۔','چکن واپس ڈال کر تھوڑا پانی دیں اور ڈھک کر نرم ہونے تک پکائیں۔','آخر میں کریم، گرم مصالحہ اور کُٹی کسوری میتھی ڈالیں۔','گریوی گاڑھی ہو تو گرم پانی یا دودھ دیں، پتلی ہو تو کھلی simmer کریں۔','پانچ منٹ آرام دے کر دھنیا کے ساتھ گرم نان پر پیش کریں۔'],idea:'کسوری میتھی کا ایک حصہ کریم کے ساتھ اور ایک چھوٹی چٹکی چولہا بند کرنے کے بعد شامل کریں۔ اس سے گہری اور تازہ دونوں خوشبو ملتی ہیں۔',serve:'بٹر نان، تندوری روٹی یا باسمتی چاول کے ساتھ پیش کریں۔',tips:['دہی پھٹ جائے تو آنچ کم کریں اور مسلسل ہلائیں۔','گریوی پتلی ہو تو کھلی پکائیں۔','چکن خشک ہو تو زیادہ تیز heat سے بچیں۔']}
  };

  function esc(s){return String(s).replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\':'&#92;','"':'&quot;'}[m]));}
  function renderEnglish(){
    const path=location.pathname.split('/').pop().replace('.html','');
    const d=(R[path]&&R[path].en); if(!d) return;
    const ing=document.querySelector('.ingredients'); if(ing) ing.innerHTML=d.ingredients.map(x=>'<li>'+esc(x)+'</li>').join('');
    const steps=document.querySelector('.steps'); if(steps) steps.innerHTML=d.steps.map((x,i)=>'<li><b>Step '+(i+1)+':</b> '+esc(x)+'</li>').join('');
    const heads=[...document.querySelectorAll('.content h2')];
    const how=heads.find(h=>/How to Make/i.test(h.textContent)); if(how && how.nextElementSibling?.classList.contains('steps')){ }
    const idea=document.querySelector('.idea'); if(idea) idea.innerHTML='<b>RecipeHub Unique Idea:</b> '+esc(d.idea);
    const serveHeads=heads.filter(h=>/Serve|Serving Suggestions/i.test(h.textContent)); if(serveHeads[0]){let p=serveHeads[0].nextElementSibling;if(p) p.textContent=d.serve;}
    const facts=[...document.querySelectorAll('.fact')]; if(facts.length){const m=d.times.match(/Prep ([^•]+) • Cook ([^•]+) •/);if(m){facts[0].querySelector('b').textContent=m[1].trim();facts[1].querySelector('b').textContent=m[2].trim();}}
    let common=[...document.querySelectorAll('.content h2')].find(h=>/Common|Kitchen Tip/i.test(h.textContent));
    if(common){let ul=common.nextElementSibling;if(ul&&ul.tagName==='UL') ul.innerHTML=d.tips.map(x=>'<li>'+esc(x)+'</li>').join('');}
  }
  function renderUrdu(){
    const key=new URLSearchParams(location.search).get('r')||'biryani';
    const d=U[key]||fallback[key]; if(!d) return;
    const t=document.getElementById('title'),i=document.getElementById('intro'),a=document.getElementById('ingredients'),s=document.getElementById('steps'),p=document.getElementById('photo');
    if(t)t.textContent=d.title;if(i)i.textContent=d.intro||d.i;if(a)a.innerHTML=(d.ingredients||d.a).map(x=>'<li>'+esc(x)+'</li>').join('');if(s)s.innerHTML=(d.steps||d.s).map(x=>'<li>'+esc(x)+'</li>').join('');
    if(d.idea){let box=document.querySelector('.box:last-of-type');if(!box){box=document.createElement('div');box.className='box';document.querySelector('main').insertBefore(box,document.querySelector('.back'));}box.innerHTML='<h2>منفرد RecipeHub آئیڈیا</h2><p>'+esc(d.idea)+'</p><h2>پیش کرنے کا طریقہ</h2><p>'+esc(d.serve||'گرم پیش کریں۔')+'</p><h2>عملی حل</h2><ul>'+d.tips.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul>'}
    if(p&&d.p)p.style.backgroundImage='url('+JSON.stringify(d.p)+')';
  }
  if(document.documentElement.lang==='ur') renderUrdu(); else renderEnglish();
})();