/* RecipeHub image loader: real food photos with recipe-key matching. */
(function(){
const I={'biryani':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Special%20Chicken%20biryani.jpg','karahi-gosht':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Karahi.JPG','daal-chawal':'https://commons.wikimedia.org/wiki/Special:Redirect/file/The%20Dal%20Chawal.jpg','nihari':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Nihari.JPG','palak-paneer':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Palak%20Paneer.JPG','butter-chicken':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Butter%20Chicken.jpg','chicken-tikka':'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&w=1200&q=80','gulab-jamun':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Gulab%20Jamun.jpg','chana-masala':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Chana%20masala.jpg','seekh-kebab':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Seekh%20Kebab.JPG','daal-makhani':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Dal%20Makhani.jpg','chicken-pulao':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Chicken%20Pulao.jpg','butter-naan':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Butter%20Naan.jpg','aloo-gobi':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Aloo%20gobi.jpg','rajma-masala':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Rajma%20Masala.jpg','kheer':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Kheer%20Special.JPG','chicken-handi':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Chicken%20Handi.JPG'};
const N={'biryani':'Chicken Biryani','karahi-gosht':'Karahi Gosht','daal-chawal':'Daal Chawal','nihari':'Nihari','palak-paneer':'Palak Paneer','butter-chicken':'Butter Chicken','chicken-tikka':'Chicken Tikka','gulab-jamun':'Gulab Jamun','chana-masala':'Chana Masala','seekh-kebab':'Seekh Kebab','daal-makhani':'Daal Makhani','chicken-pulao':'Chicken Pulao','butter-naan':'Butter Naan','aloo-gobi':'Aloo Gobi','rajma-masala':'Rajma Masala','kheer':'Kheer','chicken-handi':'Chicken Handi'};
function pageKey(){return new URLSearchParams(location.search).get('r')||location.pathname.split('/').pop().replace('.html','')}
function keyForPhoto(el){let k=el.dataset.recipe||null;const a=el.closest('a');if(!k&&a){try{k=new URL(a.href,location.href).searchParams.get('r')}catch(e){}}if(!k){const card=el.closest('.card,.recipe-card');const link=card&&card.querySelector('a[href*="?r="]');if(link){try{k=new URL(link.href,location.href).searchParams.get('r')}catch(e){}}}return k}
function mount(el,k){if(!el||!I[k]||el.dataset.rhImageMounted)return;el.dataset.rhImageMounted='1';el.style.backgroundImage='none';const img=document.createElement('img');img.src=I[k];img.alt=N[k]+' recipe';img.loading='lazy';img.decoding='async';img.style.cssText='display:block;width:100%;height:100%;object-fit:cover;object-position:center;border:0';img.onerror=function(){this.onerror=null;this.src=I[k]};el.innerHTML='';el.appendChild(img)}
function fix(){const pk=pageKey();document.querySelectorAll('.photo').forEach(el=>{const k=keyForPhoto(el)||pk;if(I[k])mount(el,k)});document.querySelectorAll('#photo,.heroimg').forEach(el=>{const k=el.dataset.recipe||pk;if(I[k])mount(el,k)});document.querySelectorAll('img[data-recipe]').forEach(img=>{const k=img.dataset.recipe;if(I[k]){img.src=I[k];img.alt=N[k]+' recipe'}})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',fix);else fix();setTimeout(fix,100);setTimeout(fix,700);setTimeout(fix,1800);
})();