/* RecipeHub image loader: keep every recipe detail image aligned with its homepage card image. */
(function(){
const I={'biryani':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Chicken%20Biryani.jpg','karahi-gosht':'https://images.deliveryhero.io/image/global-menu-service/FP_PK/vendor/u3wr/product/41eb2355-1435-4e2a-a63a-242e20312a12.jpg?width=900','daal-chawal':'https://commons.wikimedia.org/wiki/Special:Redirect/file/The%20Dal%20Chawal.jpg','nihari':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Nihari.JPG','palak-paneer':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Palak%20Paneer.JPG','butter-chicken':'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=1400&q=85','chicken-tikka':'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&w=1400&q=85','gulab-jamun':'https://images.unsplash.com/photo-1593701461250-d7b22dfd3a77?auto=format&fit=crop&w=1400&q=85','chana-masala':'https://indianhealthyrecipe.com/wp-content/uploads/2024/01/2023_01_25_creamy_chana_masala_1.jpg','seekh-kebab':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Seekh%20Kabab%202.JPG','daal-makhani':'https://images.pexels.com/photos/37182514/pexels-photo-37182514/free-photo-of-delicious-indian-dal-makhani-in-metal-bowl.jpeg?auto=compress&dpr=1&h=750&w=1260','chicken-pulao':'https://images.deliveryhero.io/image/fd-pk/Products/76532734.jpg?width=900','butter-naan':'https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy%2Cf_auto%2Cq_auto%2Cw_900%2Ch_700%2Cc_fit/FOOD_CATALOG/IMAGES/CMS/2025/12/10/f4a8a2cb-959c-47c5-a6b0-d2e82f249efd_d8b3f273-049d-4d03-8c10-52eb127063cf.jpg','aloo-gobi':'https://kababcurryalbuquerque.com/pluto-images/funnel/images/95c1175e-200e-44ae-b125-c6c73c8e9263?fit=cover&w=900','rajma-masala':'https://images.squarespace-cdn.com/content/v1/65903c4616345c144c2ac699/c8734e44-7bcc-4ae9-b2d9-7959952d1824/RajmaMasala.jpg','kheer':'https://upload.wikimedia.org/wikipedia/commons/6/6d/Kheer_Special.JPG','chicken-handi':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Punjabi%20Chicken%20Handi.JPG'};
const N={'biryani':'Chicken Biryani','karahi-gosht':'Karahi Gosht','daal-chawal':'Daal Chawal','nihari':'Nihari','palak-paneer':'Palak Paneer','butter-chicken':'Butter Chicken','chicken-tikka':'Chicken Tikka','gulab-jamun':'Gulab Jamun','chana-masala':'Chana Masala','seekh-kebab':'Seekh Kebab','daal-makhani':'Daal Makhani','chicken-pulao':'Chicken Pulao','butter-naan':'Butter Naan','aloo-gobi':'Aloo Gobi','rajma-masala':'Rajma Masala','kheer':'Kheer','chicken-handi':'Chicken Handi'};
function pageKey(){
  const direct=new URLSearchParams(location.search).get('r');
  if(direct&&I[direct])return direct;
  /* Urdu detail pages are shared by all recipes. When the language switch opens
     /ur/recipe.html without ?r=..., recover the recipe slug from the English
     recipe page that opened it instead of falling back to Chicken Biryani. */
  if(location.pathname.includes('/ur/recipe.html')&&document.referrer){
    try{
      const ref=new URL(document.referrer);
      const m=ref.pathname.match(/\/recipes\/([^/]+)\.html$/);
      if(m&&I[m[1]])return m[1];
    }catch(e){}
  }
  return direct||location.pathname.split('/').pop().replace('.html','');
}
function keyForPhoto(el){let k=el.dataset.recipe||null;const a=el.closest('a');if(!k&&a){try{k=new URL(a.href,location.href).searchParams.get('r')}catch(e){}}if(!k){const card=el.closest('.card,.recipe-card');const link=card&&card.querySelector('a[href*="?r="]');if(link){try{k=new URL(link.href,location.href).searchParams.get('r')}catch(e){}}}return k}
function mount(el,k){if(!el||!I[k]||el.dataset.rhImageMounted)return;el.dataset.rhImageMounted='1';const original=el.style.backgroundImage;const img=document.createElement('img');img.alt=N[k]+' recipe';img.loading='lazy';img.decoding='async';img.style.cssText='display:block;width:100%;height:100%;object-fit:cover;object-position:center;border:0';img.onload=function(){el.style.backgroundImage='none';el.innerHTML='';el.appendChild(img)};img.onerror=function(){el.dataset.rhImageMounted='';img.remove();if(original)el.style.backgroundImage=original};img.src=I[k]}
function fix(){const pk=pageKey();document.querySelectorAll('.photo').forEach(el=>{const k=keyForPhoto(el)||pk;if(I[k])mount(el,k)});document.querySelectorAll('#photo,.heroimg').forEach(el=>{const k=el.dataset.recipe||pk;if(I[k])mount(el,k)});document.querySelectorAll('img[data-recipe]').forEach(img=>{const k=img.dataset.recipe;if(I[k]){const old=img.src;img.onload=function(){img.alt=N[k]+' recipe'};img.onerror=function(){img.src=old};img.src=I[k];img.alt=N[k]+' recipe'}})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',fix);else fix();setTimeout(fix,150);setTimeout(fix,800);setTimeout(fix,2000);
})();